package com.cattle.dao;

import com.cattle.pojo.KeyWords;
import com.cattle.pojo.KeyWordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KeyWordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    int countByExample(KeyWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    int deleteByExample(KeyWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    int insert(KeyWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    int insertSelective(KeyWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    List<KeyWords> selectByExample(KeyWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    KeyWords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") KeyWords record, @Param("example") KeyWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") KeyWords record, @Param("example") KeyWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KeyWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywords_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KeyWords record);
}