package com.cattle.dao;

import com.cattle.pojo.Remark;
import com.cattle.pojo.RemarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int countByExample(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int deleteByExample(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int insert(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int insertSelective(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    List<Remark> selectByExampleWithBLOBs(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    List<Remark> selectByExample(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    Remark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Remark record, @Param("example") RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Remark record, @Param("example") RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Remark record, @Param("example") RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Remark record);
}