package com.cattle.pojo;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_table.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_table.pictureName
     *
     * @mbggenerated
     */
    private String picturename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_table.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_table.id
     *
     * @return the value of picture_table.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_table.id
     *
     * @param id the value for picture_table.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_table.pictureName
     *
     * @return the value of picture_table.pictureName
     *
     * @mbggenerated
     */
    public String getPicturename() {
        return picturename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_table.pictureName
     *
     * @param picturename the value for picture_table.pictureName
     *
     * @mbggenerated
     */
    public void setPicturename(String picturename) {
        this.picturename = picturename == null ? null : picturename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_table.path
     *
     * @return the value of picture_table.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_table.path
     *
     * @param path the value for picture_table.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}