package com.cattle.pojo;

public class Remark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remark_table.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remark_table.star
     *
     * @mbggenerated
     */
    private Float star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remark_table.movie
     *
     * @mbggenerated
     */
    private Integer movie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remark_table.remarkTime
     *
     * @mbggenerated
     */
    private Integer remarktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remark_table.user
     *
     * @mbggenerated
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remark_table.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remark_table.userIP
     *
     * @mbggenerated
     */
    private String userip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remark_table.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remark_table.id
     *
     * @return the value of remark_table.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remark_table.id
     *
     * @param id the value for remark_table.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remark_table.star
     *
     * @return the value of remark_table.star
     *
     * @mbggenerated
     */
    public Float getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remark_table.star
     *
     * @param star the value for remark_table.star
     *
     * @mbggenerated
     */
    public void setStar(Float star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remark_table.movie
     *
     * @return the value of remark_table.movie
     *
     * @mbggenerated
     */
    public Integer getMovie() {
        return movie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remark_table.movie
     *
     * @param movie the value for remark_table.movie
     *
     * @mbggenerated
     */
    public void setMovie(Integer movie) {
        this.movie = movie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remark_table.remarkTime
     *
     * @return the value of remark_table.remarkTime
     *
     * @mbggenerated
     */
    public Integer getRemarktime() {
        return remarktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remark_table.remarkTime
     *
     * @param remarktime the value for remark_table.remarkTime
     *
     * @mbggenerated
     */
    public void setRemarktime(Integer remarktime) {
        this.remarktime = remarktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remark_table.user
     *
     * @return the value of remark_table.user
     *
     * @mbggenerated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remark_table.user
     *
     * @param user the value for remark_table.user
     *
     * @mbggenerated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remark_table.userId
     *
     * @return the value of remark_table.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remark_table.userId
     *
     * @param userid the value for remark_table.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remark_table.userIP
     *
     * @return the value of remark_table.userIP
     *
     * @mbggenerated
     */
    public String getUserip() {
        return userip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remark_table.userIP
     *
     * @param userip the value for remark_table.userIP
     *
     * @mbggenerated
     */
    public void setUserip(String userip) {
        this.userip = userip == null ? null : userip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remark_table.comment
     *
     * @return the value of remark_table.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remark_table.comment
     *
     * @param comment the value for remark_table.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}